const AlbumsList = [
  {
    id: 1,
    img: "../../Images/Rectangle21.png",
    title: "No More Parties",
    artist: "Young Reese",
    type: "single",
    duration: "4:32",
  },
  {
    id: 2,
    img: "../../Images/Rectangle14-1.png",
    title: "Yosemite",
    artist: "Gunna ft Travis scott",
    type: "single",
    duration: "12:02",
  },
  {
    id: 3,
    img: "../../Images/Rectangle14-2.png",
    title: "Blinding Lights",
    artist: "The Weeknd",
    type: "single",
    duration: "4:32",
  },
  {
    id: 4,
    img: "../../Images/Rectangle14-3.png",
    title: "Location",
    artist: "Dave ft Burna Boy",
    type: "African Giant",
    duration: "2:30",
  },
  {
    id: 5,
    img: "../../Images/Rectangle14.png",
    title: "No More Parties",
    artist: "Young Reese",
    type: "single",
    duration: "2:52",
  },
  {
    id: 6,
    img: "../../Images/Rectangle20.png",
    title: "No More Parties",
    artist: "Young Reese",
    type: "single",
    duration: "2:22",
  },
  {
    id: 7,
    img: "../../Images/Rectangle14-2.png",
    title: "No More Parties",
    artist: "Young Reese",
    type: "single",
    duration: "3:12",
  },
  {
    id: 8,
    img: "../../Images/Rectangle181.png",
    title: "No More Parties",
    artist: "Young Reese",
    type: "single",
    duration: "1:15",
  },
  {
    id: 9,
    img: "../../Images/Rectangle14-2.png",
    title: "No More Parties",
    artist: "Young Reese",
    type: "Album",
    duration: "1:21:32",
  },
  {
    id: 10,
    img: "../../Images/Rectangle14-3.png",
    title: "No More Parties",
    artist: "Young Reese",
    type: "single",
    duration: "4:21",
  },
];

export default AlbumsList;
